version: "3.9"
services:
  db:
    image: postgres:16
    container_name: paystreet-pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: paystreet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: paystreet-redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
